
### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
spring:jmx.enabled: false

spring.thymeleaf.cache: false

spring.logging:
  level:
      org.springframework.web: INFO
      com.fico: INFO
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /home/nc/workspace/fico/myCartApp/src/main/resources/application.log

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:\Users/niteenchougula/Documents/workspace/spring-boot-batch/src/main/resources;AUTO_SERVER=TRUE
    
spring.jpa.hibernate.ddl-auto: update    
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
 
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/med17?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    platform: mysql
#  jpa:
#    hibernate.ddl-auto:  update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8090

spring:
  profiles: test
  mail:    host: smtp.gmail.com
    port: 587
    username: niteen2010@gmail.com
    password: DiyaNit!1
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
             enable: true


    
 
