
### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
spring:jmx.enabled: false

spring.thymeleaf.cache: false

spring.logging:
  level:
      org.springframework.web: INFO
      com.fico: INFO
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /home/nc/workspace/fico/myCartApp/src/main/resources/application.log

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:\I:\myApplicationDb;AUTO_SERVER=TRUE
    
spring.jpa.hibernate.ddl-auto: update    
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
 
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/med17?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    platform: mysql
#  jpa:
#    hibernate.ddl-auto:  update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-Demo
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---
spring:
  profiles: test

    
 
